# Generated by Django 5.1.1 on 2024-10-07 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soporte', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Descripcion',
            fields=[
                ('id_descripcion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id_salon', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_salon', models.CharField(max_length=25)),
                ('codigo_salon', models.IntegerField()),
                ('pabellon_salon', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id_subcategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_subcategoria', models.CharField(max_length=100)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategoria', to='usuario.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='id_subcategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.subcategoria'),
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id_incidencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_incidencia', models.DateField(auto_now_add=True)),
                ('estado_incidencia', models.CharField(default='por atender', max_length=25)),
                ('detalles_categoria', models.TextField()),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.categoria')),
                ('id_receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias_recibidas', to='soporte.soporte')),
                ('id_salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.salon')),
                ('id_emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias_enviadas', to='usuario.usuario')),
            ],
        ),
    ]
