# Generated by Django 5.1.1 on 2024-10-07 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='id_subcategoria',
        ),
        migrations.RemoveField(
            model_name='subcategoria',
            name='id_categoria',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='id_categoria',
        ),
        migrations.DeleteModel(
            name='Descripcion',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='id_emisor',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='id_receptor',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='id_salon',
        ),
        migrations.DeleteModel(
            name='Subcategoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Incidencia',
        ),
        migrations.DeleteModel(
            name='Salon',
        ),
    ]
