# Generated by Django 5.1.1 on 2024-10-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soporte',
            fields=[
                ('id_soporte', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_soporte', models.CharField(max_length=100)),
                ('contrasena_soporte', models.CharField(max_length=100)),
            ],
        ),
    ]
