# Generated by Django 5.1.1 on 2024-10-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
