# Generated by Django 5.1.1 on 2024-10-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0002_incidencia_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='emisor',
            field=models.CharField(max_length=100),
        ),
    ]
