# Generated by Django 5.1.1 on 2024-10-09 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0002_categoria_descripcion_salon_usuario_subcategoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='id_subcategoria',
            field=models.ForeignKey(db_column='id_subcategoria', null=True, on_delete=django.db.models.deletion.CASCADE, to='soporte.subcategoria'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='id_categoria',
            field=models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='soporte.categoria'),
        ),
    ]
