# Generated by Django 5.1.1 on 2024-10-09 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0003_alter_categoria_id_subcategoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='id_subcategoria',
        ),
        migrations.AddField(
            model_name='descripcion',
            name='id_subcategoria',
            field=models.ForeignKey(db_column='id_subcategoria', null=True, on_delete=django.db.models.deletion.CASCADE, to='soporte.subcategoria'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='id_categoria',
            field=models.ForeignKey(db_column='id_categoria', null=True, on_delete=django.db.models.deletion.CASCADE, to='soporte.categoria'),
        ),
    ]
