# Generated by Django 5.1.1 on 2024-10-10 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0005_alter_descripcion_id_subcategoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidencia',
            name='id_emisor',
        ),
        migrations.AddField(
            model_name='incidencia',
            name='id_descripcion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='soporte.descripcion'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='id_subcategoria',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='soporte.subcategoria'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='nombre_emisor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='estado_incidencia',
            field=models.CharField(default='Por atender', max_length=25),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='id_categoria',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='soporte.categoria'),
        ),
    ]
