# Generated by Django 5.1.1 on 2024-10-10 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0006_remove_incidencia_id_emisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='nombre_emisor',
            field=models.CharField(max_length=50),
        ),
    ]
