# Generated by Django 5.1.1 on 2024-10-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0007_alter_incidencia_nombre_emisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='detalles_categoria',
            field=models.TextField(null=True),
        ),
    ]
